import { Outfit } from "next/font/google";
import "./globals.css";
//* Component
import Header from "@/components/Header";
import Footer from "@/components/Footer";
//* Theme Provider
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "react-hot-toast";


const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Mahsa Alizolfi-Frontend Developer.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ThemeProvider attribute="class" defaultTheme='light'>
          <Header />
          {children}
          <Toaster/>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
